#!/usr/bin/env node
// balance-answers.mjs
// ---------------------------------------------------------------------------
// Re-balance the correct-answer distribution in Reading + Listening so that
// A / B / C / D each occur ~25% of the time (per level via round-robin).
//
// Each question's `options` array is reordered so the correct answer lands
// at the target letter; the remaining 3 distractors keep their relative
// order. `answer` is updated accordingly. References to option letters in
// the `ex` (explanation) string are remapped using the new letter mapping.
//
// Usage:  node scripts/balance-answers.mjs
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');

const FILES = [
  {
    label: 'READING',
    srcPath: path.join(ROOT, 'src', 'reading-complete.js'),
    exportName: 'READING',
    header: [
      '// JFLT Reading Complete — Balanced answer distribution',
      '// Distribution: L1=10+ / L2=35 / L3=25 / L4=10 (Total: 140 questions)',
      '//',
      '// Generated by scripts/balance-answers.mjs — do not hand-shuffle option',
      '// order; rerun the script if balance drifts.',
      '',
      'export const READING = {',
    ].join('\n'),
  },
  {
    label: 'LISTENING',
    srcPath: path.join(ROOT, 'src', 'listening-complete.js'),
    exportName: 'LISTENING',
    header: [
      '// JFLT Listening Complete — Balanced answer distribution',
      '// Distribution: L1=15 / L2=35 / L3=25 / L4=15 (Total: 90 questions)',
      '',
      'export const LISTENING = {',
    ].join('\n'),
  },
];

// Per-level offset so L1 doesn't always start with A, etc.
const LEVEL_OFFSET = { 1: 0, 2: 1, 3: 2, 4: 3 };

const LETTERS = ['A', 'B', 'C', 'D'];

// Verbs / context words that commonly follow an option-letter reference.
// Used to safely identify "A is", "C reverses", etc. without false-matching
// stand-alone uppercase letters.
const VERB_TOKENS = [
  'is', 'are', 'was', 'were',
  'paraphrases', 'paraphrase',
  'reverses', 'reverse',
  'captures', 'capture',
  'reads', 'read',
  'matches', 'match',
  'maps', 'map',
  'identifies', 'identify',
  'fabricates', 'fabricate', 'fabricated',
  'misreads', 'misread',
  'contradicts', 'contradict',
  'inverts', 'invert',
  'uses', 'use',
  'introduces', 'introduce',
  'references', 'reference',
  'gets', 'get',
  'misses', 'miss',
  'adds', 'add',
  'states', 'state',
  'reflects', 'reflect',
  'distorts', 'distort',
  'oversimplifies',
  'sounds',
  'looks',
  'represents',
  'mischaracterises', 'mischaracterizes',
  'narrows', 'narrow',
  'broadens', 'broaden',
];

const VERB_GROUP = VERB_TOKENS.join('|');

/**
 * Build a placeholder-based remap of A/B/C/D references in `ex`.
 * Phase 1: replace recognised references with __X__ placeholders.
 * Phase 2: substitute placeholders with the new letters from `map`.
 * Phase 3: collect any remaining bare A/B/C/D words for warning output.
 */
function remapExplanation(ex, map) {
  if (!ex || typeof ex !== 'string') return { text: ex, warnings: [] };
  let text = ex;

  // 1a. "option A" / "Option A" / "options A and B" — case-preserving
  text = text.replace(/\b(option |Option |options |Options )([ABCD])\b/g,
    (_m, prefix, l) => `${prefix}__${l}__`);

  // 1b. "Distractor A" / "distractor A"
  text = text.replace(/\b(Distractor |distractor |Distractors |distractors )([ABCD])\b/g,
    (_m, prefix, l) => `${prefix}__${l}__`);

  // 1c. "A and B" / "A and B and C" comma-and combinations
  text = text.replace(/\b([ABCD]) and ([ABCD])\b/g,
    (_m, l1, l2) => `__${l1}__ and __${l2}__`);

  // 1d. "A, B" / "A, B, C" / "A, B, and C"
  text = text.replace(/\b([ABCD]), ([ABCD])(?:, ([ABCD]))?(?:,? and ([ABCD]))?\b/g,
    (_m, l1, l2, l3, l4) => {
      let s = `__${l1}__, __${l2}__`;
      if (l3) s += `, __${l3}__`;
      if (l4) s += `, and __${l4}__`;
      return s;
    });

  // 1e. "A <verb>" — e.g. "A is too broad"
  const verbRe = new RegExp(`\\b([ABCD]) (${VERB_GROUP})\\b`, 'g');
  text = text.replace(verbRe, (_m, l, v) => `__${l}__ ${v}`);

  // Phase 2: apply mapping
  text = text.replace(/__([ABCD])__/g, (_m, l) => map[l] || l);

  // Phase 3: detect surviving bare letter references that may indicate
  // missed remap (heuristic: a single uppercase A/B/C/D surrounded by
  // word-break boundaries, not part of an acronym).
  const warnings = [];
  const bareRe = /(?<![A-Za-z])([ABCD])(?![A-Za-z])/g;
  let m;
  while ((m = bareRe.exec(text)) != null) {
    const start = Math.max(0, m.index - 25);
    const end = Math.min(text.length, m.index + 30);
    const snippet = text.slice(start, end);
    // Filter out trivially benign cases: e.g., the letter starts a sentence
    // followed by a different verb pattern, or it's at the very end (period).
    warnings.push({ letter: m[1], snippet });
  }

  return { text, warnings };
}

/**
 * Reorder `options` so that correct answer lands at `targetIdx`. Other
 * three options keep their relative order. Returns { options, oldToNew }
 * where oldToNew[oldIdx] = newIdx.
 */
function reorderOptions(options, correctIdx, targetIdx) {
  if (correctIdx === targetIdx) {
    return {
      options: options.slice(),
      oldToNew: { 0: 0, 1: 1, 2: 2, 3: 3 },
    };
  }
  // Take the correct answer out
  const correctOpt = options[correctIdx];
  const rest = options.filter((_, i) => i !== correctIdx);
  // Insert at targetIdx
  const newOpts = [];
  let restPtr = 0;
  for (let i = 0; i < 4; i++) {
    if (i === targetIdx) newOpts.push(correctOpt);
    else newOpts.push(rest[restPtr++]);
  }

  // Build oldToNew map.
  // Build it by tracking where each old index ended up.
  const oldToNew = {};
  oldToNew[correctIdx] = targetIdx;
  let writeIdx = 0;
  for (let oldIdx = 0; oldIdx < 4; oldIdx++) {
    if (oldIdx === correctIdx) continue;
    while (writeIdx === targetIdx) writeIdx++;
    oldToNew[oldIdx] = writeIdx;
    writeIdx++;
  }
  return { options: newOpts, oldToNew };
}

/**
 * Convert per-question record to a stable, compact 1-line representation
 * matching the existing style in the source files.
 */
function formatQuestion(q) {
  const parts = [];
  parts.push(`topic: ${JSON.stringify(q.topic)}`);
  if (q.passage !== undefined) parts.push(`passage: ${JSON.stringify(q.passage)}`);
  parts.push(`question: ${JSON.stringify(q.question)}`);
  parts.push(`options: [${q.options.map((o) => JSON.stringify(o)).join(', ')}]`);
  parts.push(`answer: ${q.answer}`);
  parts.push(`ex: ${JSON.stringify(q.ex)}`);
  return `    { ${parts.join(', ')} }`;
}

function distributionOf(dict) {
  const counts = { A: 0, B: 0, C: 0, D: 0 };
  for (const lvKey of Object.keys(dict)) {
    for (const q of dict[lvKey]) counts[LETTERS[q.answer]]++;
  }
  return counts;
}

async function processFile(spec) {
  console.log(`\n========== ${spec.label} ==========`);
  const mod = await import(pathToFileURL(spec.srcPath).href);
  const data = mod[spec.exportName];
  if (!data) throw new Error(`No export ${spec.exportName} in ${spec.srcPath}`);

  const before = distributionOf(data);
  console.log('Before:', before);

  const allWarnings = [];
  const balanced = {};

  for (const lvKey of Object.keys(data).sort()) {
    const lv = Number(lvKey);
    const questions = data[lvKey];
    const offset = LEVEL_OFFSET[lv] ?? 0;
    const out = [];
    for (let i = 0; i < questions.length; i++) {
      const q = questions[i];
      const targetIdx = (offset + i) % 4;
      const { options: newOpts, oldToNew } = reorderOptions(
        q.options, q.answer, targetIdx);
      // letterMap[oldLetter] = newLetter
      const letterMap = {};
      for (const [oldIdx, newIdx] of Object.entries(oldToNew)) {
        letterMap[LETTERS[oldIdx]] = LETTERS[newIdx];
      }
      const { text: newEx, warnings } = remapExplanation(q.ex, letterMap);
      if (warnings.length > 0) {
        for (const w of warnings) {
          allWarnings.push({
            level: lv,
            qIdx: i,
            topic: q.topic,
            letter: w.letter,
            snippet: w.snippet,
            map: letterMap,
          });
        }
      }
      out.push({
        ...q,
        options: newOpts,
        answer: targetIdx,
        ex: newEx,
      });
    }
    balanced[lv] = out;
  }

  const after = distributionOf(balanced);
  console.log('After: ', after);
  console.log(`Modified: ${Object.values(balanced).reduce((s, a) => s + a.length, 0)} questions`);

  // Serialise back
  const lines = [spec.header];
  for (const lvKey of Object.keys(balanced).sort()) {
    lines.push(`  ${lvKey}: [`);
    const qs = balanced[lvKey];
    lines.push(qs.map(formatQuestion).join(',\n'));
    lines.push('  ],');
  }
  lines.push('};');
  lines.push('');

  writeFileSync(spec.srcPath, lines.join('\n'), { encoding: 'utf8' });
  console.log(`Wrote ${spec.srcPath}`);

  return allWarnings;
}

const allWarnings = [];
for (const spec of FILES) {
  const w = await processFile(spec);
  allWarnings.push(...w.map((x) => ({ ...x, file: spec.label })));
}

console.log('\n========== WARNINGS ==========');
if (allWarnings.length === 0) {
  console.log('None. All option-letter references remapped cleanly.');
} else {
  console.log(`${allWarnings.length} potentially-unrecognised letter reference(s):`);
  for (const w of allWarnings) {
    console.log(`  [${w.file} L${w.level} Q${w.qIdx}] "${w.topic}"`);
    console.log(`    letter '${w.letter}' near: …${w.snippet}…`);
    console.log(`    map: ${JSON.stringify(w.map)}`);
  }
  console.log('\nReview these manually; they may be benign (e.g., article "A vehicle")');
  console.log('or may need an Edit pass to fix the explanation.');
}
